POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRvdGUiLCJpZCI6IjY3NTA4OTIzYTU0NzNjY2IwYzQyOTRmZSIsImlhdCI6MTczMzMzMTQ0MCwiZXhwIjoxNzMzMzM1MDQwfQ.zmbAM8u0n4E_KbIAQovseHTem99Bek90OVGonx4eRdI

{
    "title": "MReal Tote",
    "author": "Tote guapote",
    "url": "www.flleida.cat",
    "likes": 999
}
 