POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6Ikpvc2UiLCJpZCI6IjY3NGU0Mjk3Y2UzZDY1ZmFmZjM0OWU1ZSIsImlhdCI6MTczMzM0NDkzMywiZXhwIjoxNzMzMzQ4NTMzfQ.dWM0tJXkn6O3iVroNJ6jkRFEIkb7sqavQMZN_edfY-E

{
    "title": "MReasl Tote",
    "author": "Tote guapote",
    "url": "www.flleida.cat",
    "likes": 999
}
 